name: Publish docker image and deploy changes

on:
    workflow_dispatch: 
    push:
        branches:
        - main
        paths:
        - 'app/**/*.py'

jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Sigin to Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

          - name: Build and push
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: ${{ secrets.TAG }}
    
    deploy:
        runs-on: self-hosted
        needs: publish
        steps:
          - name: Deploy application on EC2
            run: |
              sudo docker stop ${{ secrets.CONTAINER }}
              sudo docker rm ${{ secrets.CONTAINER }}
              sudo docker pull ${{ secrets.TAG }}
              sudo docker run -d --name ${{ secrets.CONTAINER }} \
                -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                -e SQLALCHEMY_DATABASE_URL=${{ secrets.SQLALCHEMY_DATABASE_URL }} \
                ${{ secrets.TAG }}
