name: FastAPI Tests

on:
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        
        steps:
          - name: Check out repository code
            uses: actions/checkout@v3
            
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.12'
                cache: 'pip'
                
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
          - name: Run tests
            run: |
                pytest --cov=app